### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by romeodelta89** [kangris-sket/wmon#1]
Installing Driver...
mkdir: cannot create directory '/wifimuxmon/': Read-only file system
cp: target '/wifimuxmon/' is not a directory
OK
Installing Utils...
OK
Creating Symlink...
ln: failed to access '$PREFIX/bin/iwmulticall': No such file or directory
ln: failed to access '$PREFIX/bin/iwmulticall': No such file or directory
OK
Fixing Permissions...
chmod: cannot access 'wifimuxmon/*': No such file or directory
chmod: cannot operate on dangling symlink '/data/data/com.termux/files/usr/bin/wsrep_sst_rsync_wan'
OK
Temporary Files Cleaning...
OK
Installation Completed! To start WiFi monitor mode just type "wmod monitor".
./install.sh: line 24:  : command not found

**Comment by Mik39907** [comment]
This still happens to me

**Comment by ghost** [comment]
Fucking still happens in 2020

**Comment by Mik39907** [comment]
> Fucking still happens in 2020

I dont remember if i found another way to get it working or not but yea this is abandoned but i think there was a way to get it working search on yt wifi monitors for termux you might find something
